### ISSUE TITLE
Can't compile with glibc >= 2.38

### ISSUE THREAD

**Issue by marco44** [lelit/pglast#131]
I think it's because of the bug fixed by this: https://github.com/pganalyze/libpg_query/pull/203 ( I get this `error: conflicting types for ‘strchrnul’; have ‘const char *(const char *, int)’` while compiling)

Maybe the libpg_query dependency should be bumped ?

Regards

**Comment by lelit** [comment]
Uhm, that seems strange, because v5 is already using the latest libpg_query 4.2.3.
Unfortunately I do not have a machine with glibc 2.38 around, so I can't test this right now.
Can you provide more details on which system you are experiencing the problem?

**Comment by marco44** [comment]
Yeah sure, an up to date archlinux. I'm trying to build https://aur.archlinux.org/packages/python-pglast . Which makes me realize that the solution is more obvious… It's trying to build 5.2... I'll ask the package maintainer to fix this :)
Sorry about this
